name: Traffic Counter

on:
  schedule:
    - cron: "0 18 * * *" # Run once daily
  workflow_dispatch:

jobs:
  update-traffic:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Run Traffic Script
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          TRAFFIC_TOKEN: ${{ secrets.TRAFFIC_TOKEN }} # MUST BE SET IN REPO SECRETS
        run: node scripts/update-traffic.js

      - name: Commit and Push
        if: success()
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add traffic-data.json traffic-stat.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update traffic stats [skip ci]" && git push)
